name: Compact display
on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push:
    branches:
      - master
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.achievements.compact.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: >-
            forker, polyglot, developer, deployer, follower, stargazer, 
            maintainer, explorer, member, infographile, gister, verified
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
